### ISSUE TITLE
Move reliability parameter from subscriber to publisher

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh#1348]
### Describe the release item

At the moment *reliability* parameter is set at subscriber declaration.
However, handling the proper setting of reliability value of any publication requires quite a complex matching strategy that may have a negative impact on performance. Moreover, propagating the subscription declaration requires a complex update/merging strategy upon interleaved declare/undeclare.

Therefore, it would be recommended to move the *reliability* parameter from the subscriber to the publisher.
Current:
```rust
let sub = session.declare_subscriber("foo").reliability(Reliability::Reliable).await.unwrap();
let pub = session.declare_publisher("foo").await.unwrap();
session.put("foo").await.unwrap();
```
New:
```rust
let sub = session.declare_subscriber("foo").await.unwrap();
let pub = session.declare_publisher("foo").reliability(Reliability::Reliable).await.unwrap();
session.put("foo").reliability(Reliability::Reliable).await.unwrap();
```
In addition, the default value of `Reliability` should be set to `Reliable` and not `BestEffort` as it is in the current version.

- [x] Rust #1305 #1353 
- [x] C https://github.com/eclipse-zenoh/zenoh-c/issues/652 https://github.com/eclipse-zenoh/zenoh-c/pull/653
- [x] C++ https://github.com/eclipse-zenoh/zenoh-cpp/issues/203
- [x] Pico https://github.com/eclipse-zenoh/zenoh-pico/issues/614 https://github.com/eclipse-zenoh/zenoh-pico/pull/630
- [x] Python https://github.com/eclipse-zenoh/zenoh-python/pull/308 https://github.com/eclipse-zenoh/zenoh-python/pull/311
- [x] Kotlin https://github.com/eclipse-zenoh/zenoh-kotlin/pull/199
- [ ] TS https://github.com/ZettaScaleLabs/zenoh-ts/issues/3

**Comment by wyfo** [comment]
For Python: https://github.com/eclipse-zenoh/zenoh-python/pull/308
@Mallets As the reliability parameter is unstable for `declare_publisher`, and as there is even no `reliability` getter for `Publisher`, should it be added to Python now?

**Comment by Mallets** [comment]
> For Python: [eclipse-zenoh/zenoh-python#308](https://github.com/eclipse-zenoh/zenoh-python/pull/308) @Mallets As the reliability parameter is unstable for `declare_publisher`, and as there is even no `reliability` getter for `Publisher`, should it be added to Python now?

Yes. If the `reliability` getter is missing in Rust, we can add it.

**Comment by milyin** [comment]
Lowering priority, only TS remains
