### ISSUE TITLE
align `clone` methods: coordination task

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1372]
### Describe the release item

after the discussion on https://github.com/eclipse-zenoh/zenoh-c/issues/549 issue the following approach for `clone` implementation was proposed
- Rust: objects which implements `undeclare` operation should not be clonable. E.g. `Publisher` should not be clonable, because if one copy is undeclared, another one ceases to work too
   - [x] https://github.com/eclipse-zenoh/zenoh/issues/1371
   ....
- zenoh-c, zenoh-pico and zenoh-cpp should either follow the behavior of Rust API or be even more restrictive in cloning (discussable)
   - [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/678
   - [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/645
   - [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/211
 
zenoh-c and zenoh-pico should pass mutable `z_loaned_xxx_t*` parameter to callback and should provide `z_take` operation for taking value from such mutable loaned reference. This allows user to either take ownership of passed value or keep it for caller. Now this is achieved by cloning `const z_loaned_xxx_t*` object.

This task can be split into 2 parts, it's enough to implement only first one for 1.0.0 release

- [x] pass mutable `z_loaned_xxx_t*` parameter to callbacks
   - [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/677
   - [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/issues/647 https://github.com/eclipse-zenoh/zenoh-pico/pull/653
   - [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/213
- [ ] provide `z_take` operation for taking value from mutable loaned reference **(API extension, can be done in 1.1)**
   - [ ] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/718
   - [ ] zenoh-pico
   - [ ] zenoh-cpp

**Comment by milyin** [comment]
Closing the issue, the "take_from_mutable" https://github.com/eclipse-zenoh/zenoh-c/pull/718 remains open, no need to covet it here anymore
