### ISSUE TITLE
Use `init_log_from_env` on all examples

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh#1414]
### Describe the feature

Activate error logging by default in the examples:

- [x] Rust https://github.com/eclipse-zenoh/zenoh/pull/1388
- [x] C https://github.com/eclipse-zenoh/zenoh-c/pull/683
- [x] C++ https://github.com/eclipse-zenoh/zenoh-cpp/pull/215
- [x] Python https://github.com/eclipse-zenoh/zenoh-python/pull/316
- [x] Kotlin https://github.com/eclipse-zenoh/zenoh-kotlin/pull/217
