### ISSUE TITLE
Ensure z_bytes example is available on all bindings

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh#1418]
### Describe the feature

It's important to show how to serialize/deserialize data through the `ZBytes`.
An example of `Protobuf` serialization should also be provided

### Basic examples:
- [x] Rust https://github.com/eclipse-zenoh/zenoh/blob/dev/1.0.0/examples/examples/z_bytes.rs
- [x] C (zenoh-c) https://github.com/eclipse-zenoh/zenoh-c/issues/687 https://github.com/eclipse-zenoh/zenoh-c/pull/708 @DenisBiryukov91 @milyin 
- [x] C (zenoh-pico) https://github.com/eclipse-zenoh/zenoh-pico/issues/662 https://github.com/eclipse-zenoh/zenoh-pico/pull/673 @sashacmc @jean-roland 
- [x] C++ https://github.com/eclipse-zenoh/zenoh-cpp/issues/216 https://github.com/eclipse-zenoh/zenoh-cpp/pull/218 @DenisBiryukov91 @yellowhatter 
- [x] Python https://github.com/eclipse-zenoh/zenoh-python/issues/318 https://github.com/eclipse-zenoh/zenoh-python/pull/325 @wyfo 
- [x] Kotlin https://github.com/eclipse-zenoh/zenoh-kotlin/issues/219 @DariusIMP 

### Protobuf example:
- [x] Rust https://github.com/eclipse-zenoh/zenoh/blob/ddcc8f1d8c114ca256df3939c303bcbdc1f80197/examples/examples/z_bytes.rs#L154
- [x] C (zenoh-c) @DenisBiryukov91 @milyin 
- [x] C (zenoh-pico) @sashacmc @jean-roland 
- [x] C++ https://github.com/eclipse-zenoh/zenoh-cpp/blob/6e72af80b18a366c7bb12ccc4eafb40e82b6c1a2/examples/universal/z_bytes.cxx#L125
- [x] Python https://github.com/eclipse-zenoh/zenoh-python/blob/90e74618e0aa16e6677c26e8a0c6ef44dfe8c7b2/examples/z_bytes.py#L72
- [x] Kotlin @DariusIMP

**Comment by DariusIMP** [comment]
On Kotlin: https://github.com/eclipse-zenoh/zenoh-kotlin/blob/main/examples/src/main/kotlin/io.zenoh/ZBytes.kt

**Comment by yellowhatter** [comment]
@DenisBiryukov91 , as Michael is off next week, let's put you on zenoh-c and I will take C++
