### ISSUE TITLE
new serialization API

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1474]
### Describe the release item

There are few problems with current serialization API / format:
- lack of performance on serializing/deserializing arrays of primitive types
- very tight relation between serializer and `ZBytes` type. It was supposed that serializer should be replaceable, but actually current serializer is nailed to `ZBytes` and we would have been obliged to support it forever, even knowing that it's suboptimal
- asymmetry: automatic serialization on write but explicit deserialization call on read

The new serialization API solves this:
- it supports writing sequences of elements without prefixing each element with it's size, significantly improving performance
- it is palced to `zenoh-ext` and explicitly calls `ZBytes`'s writer/reader, without integration to `ZBytes`
- there is a pair of functions `z_seialize` / `z_deserialize` called explicitly

Here are tasks/PRs related to new API

- [x] zenoh https://github.com/eclipse-zenoh/zenoh/pull/1473
- [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/720
- [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/691
- [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/238
- [x] python https://github.com/eclipse-zenoh/zenoh-python/pull/344
- [x] kotlin https://github.com/eclipse-zenoh/zenoh-kotlin/pull/246
- [x] de-unstable https://github.com/eclipse-zenoh/zenoh/pull/1492
   - [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/730
   - [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/701
   - [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/239
- [x] update plugins
   - [x] https://github.com/eclipse-zenoh/zenoh-backend-influxdb/pull/243
   - [x] https://github.com/eclipse-zenoh/zenoh-backend-filesystem/pull/236
   - [x] https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/pull/223
   - [x] https://github.com/eclipse-zenoh/zenoh-backend-s3/pull/191
   - [x] https://github.com/eclipse-zenoh/zenoh-plugin-dds/pull/351
   - [x] https://github.com/eclipse-zenoh/zenoh-plugin-ros1/pull/171
   - [x] https://github.com/eclipse-zenoh/zenoh-plugin-webserver/pull/188
   - [x] https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/232
   - [x] https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/279
 - import zenoh ext wiht internal feature
   - [x] https://github.com/eclipse-zenoh/zenoh-c/pull/732
   - [x] https://github.com/eclipse-zenoh/zenoh-c/pull/733
   - [x] kotlin

**Comment by Charles-Schleich** [comment]
@milyin : DDS PR
https://github.com/eclipse-zenoh/zenoh-plugin-dds/pull/351

**Comment by Charles-Schleich** [comment]
@milyin : Ros2DDS PR 
https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/279
