### ISSUE TITLE
check/update plugins and backends to compatibility with latest API changes (encodings, etc)

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1529]
### Describe the release item

  - [x] zenoh-backend-influxdb
  - [x] zenoh-backend-filesystem
  - [x] zenoh-backend-rocksdb
  - [x] zenoh-backend-s3
  - [x] zenoh-plugin-dds
  - [x] zenoh-plugin-ros1
  - [x] zenoh-plugin-webserver
  - [x] https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/244
  - [x] zenoh-ext API zenoh-plugin-ros2dds
