### ISSUE TITLE
Add Querier to all bindings

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1620]
### Describe the release item

- [x] zenoh https://github.com/eclipse-zenoh/zenoh/pull/1591
- [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/837
- [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/858
- [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/297
- [x] zenoh-python https://github.com/eclipse-zenoh/zenoh-python/pull/399
- [x] zenoh-kotlin https://github.com/eclipse-zenoh/zenoh-kotlin/pull/316
- [x] zenoh-ts https://github.com/eclipse-zenoh/zenoh-ts/pull/64
