### ISSUE TITLE
stabilize liveliness API

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1645]
### Describe the release item

- [x] zenoh https://github.com/eclipse-zenoh/zenoh/pull/1646
- [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/853
- [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/825
- [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/314
- [x] zenoh-python https://github.com/eclipse-zenoh/zenoh-python/pull/410
- [x] zenoh-kotlin was not marked as unstable
- [x] zenoh-ts no unstable setting
- [x] zenoh-java - not a requirement at this moment
