### ISSUE TITLE
Make sure that zenoh passes the Rust style guide

### ISSUE THREAD

**Issue by esteve** [eclipse-zenoh/zenoh#33]
I've broken up the diff per package so that they are easier to review and they can be put on hold if someone is actively working on any of them.

 - [x] plugins/example-plugin #25
 - [x] plugins/zenoh-http #26
 - [x] zenoh #27
 - [x] zenoh-util #28 
 - [x] zenoh-router #29 
 - [x] zenoh-protocol #30 
 - [x] zenoh-perf #31 
 - [x] zenoh-ffi #32 

Once all the PR are merged, we can merge this one that will run `rustfmt` on CI:

 - [x] Run rustfmt as part of CI #24

**Comment by kydos** [comment]
OK. Sounds good.

**Comment by JEnoch** [comment]
Done, all was merged.

**Comment by esteve** [comment]
@kydos @JEnoch thanks!
