### ISSUE TITLE
Bindings alingmemt

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#690]
The list of API alignment issues

- [x] https://github.com/eclipse-zenoh/zenoh/issues/1348 (coordination task)
- [x] https://github.com/eclipse-zenoh/zenoh/issues/1372 (coordination task)
- [x] remove `config::client` and `config::peer`
   - [x] zenoh To be done as part of https://github.com/eclipse-zenoh/zenoh/issues/1069
   - [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/669
   - [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/641
   - [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/210
- [x] https://github.com/eclipse-zenoh/zenoh-cpp/issues/200
- [x] arc-session
   - [x] zenoh https://github.com/eclipse-zenoh/zenoh/pull/1364 
   - [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/676
   - [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/652, https://github.com/eclipse-zenoh/zenoh-pico/pull/655
   - [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/211
 - [x] `z_open_options_t`, `z_close_options_t` parameters for `z_open`, `z_close` 
   - [x] zenoh-c https://github.com/eclipse-zenoh/zenoh-c/issues/352, https://github.com/eclipse-zenoh/zenoh-c/pull/667
   - [x] zenoh-pico https://github.com/eclipse-zenoh/zenoh-pico/pull/637
   - [x] zenoh-cpp https://github.com/eclipse-zenoh/zenoh-cpp/pull/211

----------------------- For 1.1
 
- [x] Liveliness token support
   - [x] https://github.com/eclipse-zenoh/zenoh-c/pull/189 
   - [x] https://github.com/eclipse-zenoh/zenoh-pico/issues/621  
   - [x] zenoh-cpp

----------------------- Cancelled ?
  - [ ] Make writer consume z_bytes_t and then return it upon finishing all writes
    - [x] https://github.com/eclipse-zenoh/zenoh-c/issues/661
    - [ ] zenoh-pico
    - [ ] zenoh-cpp

 - [ ] Opaque callback, shared reference in callback parameter. Rust API change, zenoh-pico and zenoh-cpp supposedly not affected
   - [ ] zenoh https://github.com/eclipse-zenoh/zenoh/pull/1383
   - [ ] zenoh-c

---------------
Make sure that all bindings and languages have a same level of documentation, compatible examples, good level of information in the README, etc.

**Comment by milyin** [comment]
Lowering priority: only config for rust and take for callback parameters remains
